MyApp/urls.py
from django.conf.urls import url
from .views import about, academic, skill, contact, form
app_name = "MyApp"
urlpatterns = [
    url(r'^$', about, name='about'),
    url(r'^academic', academic, name='academic'),
    url(r'^skill', skill, name='skill'),
    url(r'^contact', contact, name='contact'),
    url(r'^form', form, name='form'),
]

PPW/urls.py
from django.contrib import admin
from django.urls import path,include
from MyApp.views import about as aboutt
from story5App.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('MyApp/', include('MyApp.urls', namespace="MyApp")),
    path('story5/', include('story5App.urls', namespace="story5App")),
    path('', aboutt, name="MyApp"),
]

story5App/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

app_name = "story5App"
urlpatterns = [
    url(r'^forms_post', forms_post, name='forms_post'),
    url(r'^forms_collection', forms_collection, name='forms_collection'),
    url(r'^forms_html', forms_html, name='forms_html'),
    url(r'^forms_delete', forms_delete, name='forms_delete')
]

MyApp/models.py
from django.db import models

# Create your models here.

story5App/models.py
from django.db import models

class formsModels(models.Model):
    name = models.CharField(max_length=27)
    date = models.DateTimeField()
    place = models.CharField(max_length=27)
    category = models.CharField(max_length=27)
    

story5App/forms.py
from django import forms

class Schedule_Form(forms.Form):
    attrs = {'class': 'form-control'}
    date = forms.DateTimeField(required=True, widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), input_formats=['%Y-%m-%dT%H:%M'])
    name = forms.CharField(label='Nama', required=True, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
    place = forms.CharField(label='Tempat', required=True, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
    category = forms.CharField(label='Kategori', required=True, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))

MyApp/views.py
from django.shortcuts import render
from django.http import HttpResponse

def about(request):
    return render(request, 'MyWeb.html')

def academic(request):
    return render(request, 'MyWeb2.html')

def skill(request):
    return render(request, 'MyWeb3.html')

def contact(request):
    return render(request, 'MyWeb4.html')

def form(request):
    return render(request, 'MyWeb5.html')



story5App/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Schedule_Form
from .models import formsModels
# Create your views here.
def forms_post(request):
    response = {}
    if(request.method == 'POST' or None):
        response['name'] = request.POST['name']
        response['date'] = request.POST['date']
        response['place'] = request.POST['place']
        response['category'] = request.POST['category']
        forms = formsModels(name=response['name'], date=response['date'], place=response['place'], category=response['category'])
        forms.save()
        html = 'Schedule_Forms.html'
        return HttpResponseRedirect('forms_collection')
        #return render(request, html, response)
    else:
        return HttpResponseRedirect('forms_post')

def forms_collection(request):
    allForms = formsModels.objects.all()
    response = {'result': allForms}
    html = 'table.html' 
    return render(request, html, response)

def forms_html(request):
    response = {'forms' : Schedule_Form}
    return render(request, "Schedule_Forms.html", response)

def forms_delete(request):
    allForms = formsModels.objects.all().delete()
    return HttpResponseRedirect('forms_collection')

MyApp/templates/MyWeb.html
<!DOCTYPE html>
<html>
	<header>{% include "partials/header.html" %}</header>
	<body>
		<div class="all">
			<div class="header-deskripsi">
				<h3 align="center" font-family="cursive">Tentang Saya</h3>
			</div>

			<div class="deskripsi" align="justify" font-family="cursive">
					Nama panggilan saya Ulhaq. Saat ini saya kuliah di Universitas Indonesia jurusan Sistem Informasi. 
					Selain belajar di kelas, saya juga suka mengikuti 
					kegiatan lain di organisasi dan kepanitiaan di kampus. Saya senang mengikuti kegiatan yang bermanfaat untuk orang lain. Selain itu, saya memiliki rasa keingintahuan yang tinggi, terutama dalam bidang teknologi.
			</div>

			<div class="bawah" border-style:"solid" border-color:"white">
				<div class="nama-lengkap">Muhammad Dhiyaulhaq Nugraha</div>

					<div class="bar">
						<nav class="navbar navbar-expand-lg navbar-light" style="background-color: F0BB32;">
							<a class="navbar-brand col-lg-2 col-xs-6" id="btn-ttg-saya" href="{% url 'MyApp:about' %}" style="background-color:rgba(255, 144, 82, 0.6); padding:0px 60px 0px 60px;">Tentang Saya</a>
							<a class="navbar-brand col-lg-3 col-xs-6" id="btn-anp" href="{% url 'MyApp:academic' %}" style="padding:0px 60px 0px 60px">Akademik & Pengalaman</a>
							<a class="navbar-brand col-lg-2 col-xs-6" id="btn-ahli" href="{% url 'MyApp:skill' %}" style="padding:0px 60px 0px 60px">Keahlian</a>
							<a class="navbar-brand col-lg-2 col-xs-6" id="btn-kntk" href="{% url 'MyApp:contact' %}" style="padding:0px 60px 0px 60px">Kontak</a>
							<a class="navbar-brand col-lg-2 col-xs-6" id="btn-kntk" href="{% url 'MyApp:form' %}" style="padding:0px 60px 0px 60px">Form</a>					
						</nav>
					</div>

					<div class="barr">
						<nav class="navbar navbar-expand-lg navbar-light fixed-bottom" style="background-color: F0BB32; margin-left: 30%;">
							<a class="navbar-brand" id="btn-ahli" href="{% url 'story5App:forms_html' %}" style="padding:0px 60px 0px 60px">Schedule Form</a>
						<a class="navbar-brand" id="btn-ahli" href="{% url 'story5App:forms_collection' %}" style="padding:0px 60px 0px 60px">Jadwal Kegiatan</a>
						</nav>
					</div>
				</div>
			</div>
		</div>
	</body>
	
</html>

MyApp/templates/MyWeb2.html
<!DOCTYPE html>
<html>
	<header>{% include "partials/header.html" %}</header>
	<body>
		<div class="all">
			<div class="header-akademik">
				<h3 align="center" font-family="cursive">Akademik</h3>
            </div>
            
            <div class="header-pengalaman">
                    <h3 align="center" font-family="cursive">Pengalaman</h3>
                </div>

			<div class="akademik" align="justify" font-family="cursive">
					<p>- Universitas Indonesia</p>
                    <p>- SMAN 5 Depok</p>
                    <p>- SMPN 3 Depok</p>
                    <p>- SD Muhammadiyah 38 Sawangan</p>
            </div>
            
            <div class="pengalaman" align="justify" font-family="cursive">
                    <p>- Ketua Forum Anak Sawangan</p>
                    <p>- Staff Science Club 5 Depok</p>
                    <p>- Sekretaris Rohis 5 Depok</p>
                    <p>- Staff COMPFEST X</p>
                    <p>- PJ Dana Pentas Seni Islam SMAN 5 Depok</p>
                    <p>- Staff Sosial dan Ilmu Politik FUKI</p>
			</div>

			<div class="bawah" border-style:"solid" border-color:"white">
				<div class="nama-lengkap">Muhammad Dhiyaulhaq Nugraha</div>

					<div class="bar">
						<nav class="navbar navbar-expand-lg navbar-light" style="background-color: F0BB32;">
							<a class="navbar-brand col-lg-2 col-xs-6" id="btn-ttg-saya" href="{% url 'MyApp:about' %}" style="padding:0px 60px 0px 60px">Tentang Saya</a>
							<a class="navbar-brand col-lg-3 col-xs-6" id="btn-anp" href="{% url 'MyApp:academic' %}" style="background-color:rgba(255, 144, 82, 0.6); padding:0px 60px 0px 60px">Akademik & Pengalaman</a>
							<a class="navbar-brand col-lg-2 col-xs-6" id="btn-ahli" href="{% url 'MyApp:skill' %}" style="padding:0px 60px 0px 60px">Keahlian</a>
							<a class="navbar-brand col-lg-2 col-xs-6" id="btn-kntk" href="{% url 'MyApp:contact' %}" style="padding:0px 60px 0px 60px">Kontak</a>
							<a class="navbar-brand col-lg-2 col-xs-6" id="btn-kntk" href="{% url 'MyApp:form' %}" style="padding:0px 60px 0px 60px">Form</a>
						</nav>
					</div>

					<div class="barr">
						<nav class="navbar navbar-expand-lg navbar-light fixed-bottom" style="background-color: F0BB32; margin-left: 30%;">
							<a class="navbar-brand" id="btn-ahli" href="{% url 'story5App:forms_html' %}" style="padding:0px 60px 0px 60px">Schedule Form</a>
						<a class="navbar-brand" id="btn-ahli" href="{% url 'story5App:forms_collection' %}" style="padding:0px 60px 0px 60px">Jadwal Kegiatan</a>
						</nav>
					</div>
				</div>
			</div>
		</div>
	</body>
	
</html>

MyApp/templates/MyWeb3.html
<!DOCTYPE html>
<html>
	<header>{% include "partials/header.html" %}</header>
	
	<body>
		<div class="all">
			<div class="header-keahlian">
				<h3 align="center" font-family="cursive">Keahlian</h3>
			</div>

			<div class="keahlian" align="justify" font-family="cursive">
                <p>Ms Word:</p>
                <p>PowerPoint:</p>
                <p>Python:</p>
                <p>Java:</p>
            </div>
            
            <div class="w3-container">
                <div class="w3-border" id="progress-bar1">
                     <div class="w3-blue" style="height:24px;width:90%">90%</div>
                </div>
            </div>
            
            <div class="w3-container">
                <div class="w3-border" id="progress-bar2">
                     <div class="w3-blue" style="height:24px;width:85%">85%</div>
                </div>
            </div>            
            
            <div class="w3-container">
                <div class="w3-border" id="progress-bar3">
                     <div class="w3-blue" style="height:24px;width:85%;">85%</div>
                </div>
            </div>

            <div class="w3-container">
                <div class="w3-border" id="progress-bar4">
                     <div class="w3-blue" style="height:24px;width:80%">80%</div>
                </div>
            </div>

			<div class="bawah" border-style:"solid" border-color:"white">
				<div class="nama-lengkap">Muhammad Dhiyaulhaq Nugraha</div>
			
				<div class="bar">
						<nav class="navbar navbar-expand-lg navbar-light" style="background-color: F0BB32;">
							<a class="navbar-brand col-lg-2 col-xs-6" id="btn-ttg-saya" href="{% url 'MyApp:about' %}" style="padding:0px 60px 0px 60px">Tentang Saya</a>
							<a class="navbar-brand col-lg-3 col-xs-6" id="btn-anp" href="{% url 'MyApp:academic' %}" style="padding:0px 60px 0px 60px">Akademik & Pengalaman</a>
							<a class="navbar-brand col-lg-2 col-xs-6" id="btn-ahli" href="{% url 'MyApp:skill' %}" style="background-color:rgba(255, 144, 82, 0.6); padding:0px 60px 0px 60px">Keahlian</a>
							<a class="navbar-brand col-lg-2 col-xs-6" id="btn-kntk" href="{% url 'MyApp:contact' %}" style="padding:0px 60px 0px 60px">Kontak</a>
							<a class="navbar-brand col-lg-2 col-xs-6" id="btn-kntk" href="{% url 'MyApp:form' %}" style="padding:0px 60px 0px 60px">Form</a>
						</nav>
                    </div>
                    
                    <div class="barr">
						<nav class="navbar navbar-expand-lg navbar-light fixed-bottom" style="background-color: F0BB32; margin-left: 30%;">
							<a class="navbar-brand" id="btn-ahli" href="{% url 'story5App:forms_html' %}" style="padding:0px 60px 0px 60px">Schedule Form</a>
						<a class="navbar-brand" id="btn-ahli" href="{% url 'story5App:forms_collection' %}" style="padding:0px 60px 0px 60px">Jadwal Kegiatan</a>
						</nav>
					</div>
			</div>
		</div>
	</body>
	
</html>

MyApp/templates/MyWeb4.html
<!DOCTYPE html>
<html>
	<header>{% include "partials/header.html" %}</header>
	
	<body style="background-color: rgba(255, 144, 82, 0.45);">
		<div class="all">
			<div class="header-kontak">
				<h3 align="center" font-family="cursive">Kontak</h3>
			</div>

			<div class="kontak" align="justify" font-family="cursive">
				<img id="img-wa" src="https://lh6.ggpht.com/mp86vbELnqLi2FzvhiKdPX31_oiTRLNyeK8x4IIrbF5eD1D5RdnVwjQP0hwMNR_JdA">
				<div id="text-wa">082112741481</div>
				<img id="img-instagram" src="https://www.edigitalagency.com.au/wp-content/uploads/instagram-logo-png-transparent-background-800x799.png">
				<div id="text-instagram">@mdhiyaulhaqn</div>
				<img id="img-email" src="https://banner2.kisspng.com/20171216/aea/gmail-logo-png-5a3553a6e082c3.6128108415134442629196.jpg">
				<div id="text-email">dhiyaulhaqnugraha@gmail.com</div>
			</div>

			<div class="bawah" border-style:"solid" border-color:"white">
				<div class="nama-lengkap">Muhammad Dhiyaulhaq Nugraha</div>
				<div class="bar">
					<nav class="navbar navbar-expand-lg navbar-light" style="background-color: F0BB32;">
						<a class="navbar-brand col-lg-2 col-xs-6" id="btn-ttg-saya" href="{% url 'MyApp:about' %}" style="padding:0px 60px 0px 60px">Tentang Saya</a>
						<a class="navbar-brand col-lg-3 col-xs-6" id="btn-anp" href="{% url 'MyApp:academic' %}" style="padding:0px 60px 0px 60px">Akademik & Pengalaman</a>
						<a class="navbar-brand col-lg-2 col-xs-6" id="btn-ahli" href="{% url 'MyApp:skill' %}" style="padding:0px 60px 0px 60px">Keahlian</a>
						<a class="navbar-brand col-lg-2 col-xs-6" id="btn-kontak" href="{% url 'MyApp:contact' %}" style="background-color:rgba(255, 144, 82, 0.6); padding:0px 60px 0px 60px">Kontak</a>
						<a class="navbar-brand col-lg-2 col-xs-6d" id="btn-kntk" href="{% url 'MyApp:form' %}" style="padding:0px 60px 0px 60px">Form</a>
					</nav>
				</div>

				<div class="barr">
					<nav class="navbar navbar-expand-lg navbar-light fixed-bottom" style="background-color: F0BB32; margin-left: 30%;">
						<a class="navbar-brand" id="btn-ahli" href="{% url 'story5App:forms_html' %}" style="padding:0px 60px 0px 60px">Schedule Form</a>
					<a class="navbar-brand" id="btn-ahli" href="{% url 'story5App:forms_collection' %}" style="padding:0px 60px 0px 60px">Jadwal Kegiatan</a>
					</nav>
				</div>
			</div>
		</div>
	</body>
	
</html>

MyApp/templates/MyWeb5.html
<!DOCTYPE html>
<html>
	<header>{% include "partials/header.html" %}</header>
	<body style="background-color: rgba(255, 144, 82, 0.45);">
		<div class="all">
			<div class="header-form">
				<h3 align="center" font-family="cursive">Buku Tamu</h3>
			</div>

			<div class="form" align="justify" font-family="cursive">
                <form class="form-group">
                    <div class="form-group form-inline">
                      <label for="exampleInputPassword1">Nama</label>
                      <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Nama" style="width:300px;margin-left:80px;">
                    </div>
                    <div class="form-group form-inline">
                      <label for="exampleInputPassword1">Tanggal</label>
                      <input type="date" class="form-control" id="exampleInputPassword1" placeholder="Tanggal" style="width:300px;margin-left:65px;">
                    </div>
                    <div class="form-group form-inline">
                      <label for="exampleInputEmail1">Email address</label>
                      <input type="email" class="form-control" id="inputEmail" aria-describedby="emailHelp" placeholder="Enter email" style="width:300px;margin-left:20px;">
                      <button type="submit" class="btn btn-primary" style="height:40px;margin-left:50px;">Submit</button>
                    </div>
                    <div class="form-group form-inline">
                      <label for="exampleInputPassword1">Subjek</label>
                      <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Subjek" style="width:300px;margin-left:70px;">
                    </div>
                    <div class="form-group form-inline">
                      <label for="exampleInputPassword1">Message</label>
                      <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Message" style="width:300px;margin-left:55px">
                    </div>
                  </form>
			</div>

			<div class="bawah" border-style:"solid" border-color:"white">
				<div class="nama-lengkap">Muhammad Dhiyaulhaq Nugraha</div>
				<div class="bar">
					<nav class="navbar navbar-expand-lg navbar-light" style="background-color: F0BB32;">
						<a class="navbar-brand col-lg-2 col-xs-6" id="btn-ttg-saya" href="{% url 'MyApp:about' %}" style="padding: 0px 60px 0px 60px;">Tentang Saya</a>
						<a class="navbar-brand col-lg-3 col-xs-6" id="btn-anp" href="{% url 'MyApp:academic' %}" style="padding:0px 60px 0px 60px">Akademik & Pengalaman</a>
						<a class="navbar-brand col-lg-2 col-xs-6" id="btn-ahli" href="{% url 'MyApp:skill' %}" style="padding:0px 60px 0px 60px">Keahlian</a>
						<a class="navbar-brand col-lg-2 col-xs-6" id="btn-kntk" href="{% url 'MyApp:contact' %}" style="padding:0px 60px 0px 60px">Kontak</a>
						<a class="navbar-brand col-lg-2 col-xs-6" id="btn-form" href="{% url 'MyApp:form' %}" style="background-color:rgba(255, 144, 82, 0.6); padding:0px 60px 0px 60px">Form</a>
					</nav>
        </div>
        <div class="barr">
          <nav class="navbar navbar-expand-lg navbar-light fixed-bottom" style="background-color: F0BB32; margin-left: 30%;">
            <a class="navbar-brand" id="btn-ahli" href="{% url 'story5App:forms_html' %}" style="padding:0px 60px 0px 60px">Schedule Form</a>
          <a class="navbar-brand" id="btn-ahli" href="{% url 'story5App:forms_collection' %}" style="padding:0px 60px 0px 60px">Jadwal Kegiatan</a>
          </nav>
        </div>
			</div>
		</div>
	</body>
	
</html>

MyApp/templates/partials/header.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Ulhaq</title>
		<link rel="stylesheet" type="text/css" href="/static/css/mystyle.css">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	</head>
	
	<body style="background-color: rgba(255, 144, 82, 0.45);">
		<div class="jumbotron text-center" id="atas">
			<div class="text-left" id="nama-panggilan">Ulhaq</div>
		</div>
		
		<div id="gambar">
			<img src="https://pbs.twimg.com/profile_images/1042423648437469185/N0XYJ4W2_400x400.jpg" class="rounded-circle img-fluid" height="50%" width="50%">
		</div> 
    </body>
</html>

story5App/templates/Schedule_Forms.html
<!DOCTYPE html>
<html>
    <header>{% include "partials/header.html" %}</header>
    <div class="all">
			<div class="header-deskripsi">
				<h3 align="center" font-family="cursive">Form Jadwal Kegiatan</h3>
			</div>

			<div class="deskripsi" align="justify" font-family="cursive" style="padding-bottom: 80px;">
                <form action={% url 'story5App:forms_post' %} method="POST">
                        {% csrf_token %}
                        {{ forms.as_p }}
                    <input type="submit" value="Submit">
                </form>
			</div>

			<div class="bawah" border-style:"solid" border-color:"white">
				<div class="nama-lengkap">Muhammad Dhiyaulhaq Nugraha</div>

					<div class="barr">
						<nav class="navbar fixed-bottom navbar-light bg-light" style="background-color: F0BB32;">
							<a class="navbar-brand col-lg-2 col-xs-6" id="btn-ttg-saya" href="{% url 'MyApp:about' %}" style="padding:0px 60px 0px 60px;">Tentang Saya</a>
							<a class="navbar-brand col-lg-3 col-xs-6" id="btn-anp" href="{% url 'MyApp:academic' %}" style="padding:0px 60px 0px 60px">Akademik & Pengalaman</a>
							<a class="navbar-brand col-lg-2 col-xs-6" id="btn-ahli" href="{% url 'MyApp:skill' %}" style="padding:0px 60px 0px 60px">Keahlian</a>
							<a class="navbar-brand col-lg-2 col-xs-6" id="btn-kntk" href="{% url 'MyApp:contact' %}" style="padding:0px 60px 0px 60px">Kontak</a>
							<a class="navbar-brand col-lg-2 col-xs-6" id="btn-kntk" href="{% url 'MyApp:form' %}" style="padding:0px 60px 0px 60px">Form</a>					
							<a class="navbar-brand" id="btn-ahli" href="{% url 'story5App:forms_html' %}" style="background-color:rgba(255, 144, 82, 0.6); padding:0px 60px 0px 60px">Schedule Form</a>
							<a class="navbar-brand" id="btn-ahli" href="{% url 'story5App:forms_collection' %}" style="padding:0px 60px 0px 60px">Jadwal Kegiatan</a>
						</nav>
					</div>

				</div>
			</div>
		</div>
</html>

story5App/templates/table.html
<!DOCTYPE html>
<html>
    <head>
        <title>Form Jadwal</title>
        <header>{% include "partials/header.html" %}</header>
    </head>
    <div style="text-align:center; font-size: 50px"> Jadwal Kegiatan </div>
    <!-- {% block title %} Kumpulan Pesan {% endblock %} -->
    <table class="table">
        <thead>
            <th>Nama</th>
            <th>Tanggal</th>
            <th>Tempat</th>
            <th>Kategori</th>
        </thead>
        <tbody>
            {% for i in result %}
                <td> {{i.name}} </td>
                <td> {{i.date}} </td>
                <td> {{i.place}} </td>
                <td> {{i.category}}</td>
            </tr>
            {% endfor %}
        </tbody>

        <a class="btn" href="{% url 'story5App:forms_delete' %}">Hapus Semua</a>
        
        <div class="bar">
            <nav class="navbar fixed-bottom navbar-light bg-light" style="background-color: F0BB32;">
                <a class="navbar-brand col-lg-2 col-xs-6" id="btn-ttg-saya" href="{% url 'MyApp:about' %}" style="padding:0px 60px 0px 60px;">Tentang Saya</a>
                <a class="navbar-brand col-lg-3 col-xs-6" id="btn-anp" href="{% url 'MyApp:academic' %}" style="padding:0px 60px 0px 60px">Akademik & Pengalaman</a>
                <a class="navbar-brand col-lg-2 col-xs-6" id="btn-ahli" href="{% url 'MyApp:skill' %}" style="padding:0px 60px 0px 60px">Keahlian</a>
                <a class="navbar-brand col-lg-2 col-xs-6" id="btn-kntk" href="{% url 'MyApp:contact' %}" style="padding:0px 60px 0px 60px">Kontak</a>
                <a class="navbar-brand col-lg-2 col-xs-6" id="btn-kntk" href="{% url 'MyApp:form' %}" style="padding:0px 60px 0px 60px">Form</a>					
                <a class="navbar-brand" id="btn-ahli" href="{% url 'story5App:forms_html' %}" style="padding:0px 60px 0px 60px">Schedule Form</a>
                <a class="navbar-brand" id="btn-ahli" href="{% url 'story5App:forms_collection' %}" style="background-color:rgba(255, 144, 82, 0.6); padding:0px 60px 0px 60px">Jadwal Kegiatan</a>
            </nav>
        </div>
        
    </table>

</html>
